---
- name: Create Docker directory
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /etc/docker
    - /opt/docker/data
    - /opt/docker/configs

- name: Configure Docker daemon
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: '0644'
  notify: restart docker

- name: Start Docker service
  launchd:
    name: com.docker.docker
    state: started
    enabled: yes

- name: Create Docker containers
  docker_container:
    name: "{{ item.name }}"
    image: "{{ item.image }}"
    ports: "{{ item.ports }}"
    volumes: "{{ item.volumes | default([]) }}"
    restart_policy: always
    state: started
  loop: "{{ docker_containers }}"
  when: docker_enabled
